# Generated by Django 3.2 on 2022-07-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('qty', models.IntegerField(default=0, verbose_name='quantity')),
                ('available_qty', models.IntegerField(default=0, verbose_name='available quantity')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(verbose_name='book checkout date')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='book return date')),
                ('is_renewed', models.BooleanField(default=False, verbose_name='is renewed')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='book')),
            ],
            options={
                'verbose_name': 'borrowed books',
                'verbose_name_plural': 'borrowed books',
            },
        ),
    ]
